In [120]:
import pandas as pd

train_data = pd.read_csv('train.csv')
gender_data = pd.read_csv('gender_submission.csv')
test_data = pd.read_csv('test.csv')

In [121]:
train_data = train_data.dropna()
test_data = test_data.dropna()

In [122]:
train_data['Sex'] = train_data['Sex'].apply(lambda x : 1 if(x=='male') else 0)
train_data['Embarked'] = train_data['Embarked'].apply(lambda x : 1 if x=='S' else 2 if x=='C' else 3 if x == 'Q' else 0 )
train_data['Embarked'].unique()
test_data['Sex'] = test_data['Sex'].apply(lambda x : 1 if(x=='male') else 0)
test_data['Embarked'] = test_data['Embarked'].apply(lambda x : 1 if x=='S' else 2 if x=='C' else 3 if x == 'Q' else 0 )
test_data['Embarked'].unique()

array([1, 2, 3], dtype=int64)

In [137]:
from sklearn.ensemble import RandomForestRegressor
features = ['Pclass','Sex','Age','SibSp','Parch','Embarked','Fare']

X = train_data[features]
y = train_data['Survived']
test_data_input = test_data[features]

In [134]:
test_data

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
12,904,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",0,23.0,1,0,21228,82.2667,B45,1
14,906,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",0,47.0,1,0,W.E.P. 5734,61.1750,E31,1
24,916,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",0,48.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,2
26,918,1,"Ostby, Miss. Helene Ragnhild",0,22.0,0,1,113509,61.9792,B36,2
28,920,1,"Brady, Mr. John Bertram",1,41.0,0,0,113054,30.5000,A21,1
...,...,...,...,...,...,...,...,...,...,...,...
404,1296,1,"Frauenthal, Mr. Isaac Gerald",1,43.0,1,0,17765,27.7208,D40,2
405,1297,2,"Nourney, Mr. Alfred (Baron von Drachstedt"")""",1,20.0,0,0,SC/PARIS 2166,13.8625,D38,2
407,1299,1,"Widener, Mr. George Dunton",1,50.0,1,1,113503,211.5000,C80,2
411,1303,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",0,37.0,1,0,19928,90.0000,C78,3
414,1306,1,"Oliva y Ocana, Dona. Fermina",0,39.0,0,0,PC 17758,108.9000,C105,2

In [138]:

rfr = RandomForestRegressor(random_state = 1)
rfr.fit(X,y)

RandomForestRegressor(random_state=1)

In [139]:
rfr_predictions = rfr.predict(test_data_input).astype('int32')
rfr_predictions

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1])

In [158]:
data = pd.DataFrame(test_data['PassengerId'],columns=['PassengerId','Survived'])
data['Survived']=rfr_predictions
data.reset_index(drop=True, inplace=True)
data.to_csv('my_predictions.csv',index=False);
data

    PassengerId  Survived
0           904         1
1           906         1
2           916         0
3           918         1
4           920         0
..          ...       ...
82         1296         0
83         1297         0
84         1299         0
85         1303         1
86         1306         1

[87 rows x 2 columns]